name: Promote to darktwebssg (Production)

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout darktweb2 (staging)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to darktwebssg (production)
        env:
          PAT: ${{ secrets.PROD_TOKEN }}
        run: |
          echo "Using Personal Access Token for authentication..."
          git config --global user.name "samithw"
          git config --global user.email "actions@github.com"

          # Add the production repo with explicit PAT auth
          git remote add prod https://samithw:${PAT}@github.com/samithw/darktwebssg.git

          # Check remotes (for debugging)
          git remote -v

          # Push main branch to production repo
          git push prod main --force
